.PHONY: all
all: out/lib/hook-functions.o out/darwin-bootstrap/safety-dance/main.o out/unrestrict out/SafetyDance.app/Info.plist out/bundle-loader.dylib out/lib/darwin/read.o out/darwin-bootstrap/safety-dance/AutoGrid.o out/darwin-bootstrap/posixspawn-hook.o out/lib/darwin/execmem.o out/substituted out/posixspawn-hook.dylib out/lib/jump-dis.o out/libsubstitute.0.dylib out/lib/darwin/find-syms.o out/lib/darwin/objc.o out/lib/darwin/interpose.o out/generated/darwin-inject-asm.o out/lib/darwin/objc-asm.o out/SafetyDance.app/Default.png out/lib/cbit/vec.o out/inject-into-launchd out/safemode-ui-hook.dylib out/darwin-bootstrap/inject-into-launchd.o out/lib/darwin/inject.o out/libsubstitute.dylib out/darwin-bootstrap/safemode-ui-hook.o out/lib/transform-dis.o out/SafetyDance.app/Default@2x.png out/lib/darwin/substrate-compat.o out/darwin-bootstrap/unrestrict.o out/SafetyDance.app/SafetyDance out/darwin-bootstrap/bundle-loader.o out/darwin-bootstrap/substituted.o out/lib/strerror.o

# Generated by mconfig.py
out/generated/darwin-inject-asm.o: generated/darwin-inject-asm.S
	mkdir -p out/generated
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/generated/darwin-inject-asm.o -MMD -MF /Users/a/open/substitute/out/generated/darwin-inject-asm.d ./generated/darwin-inject-asm.S
-include out/generated/darwin-inject-asm.d

out/lib/darwin/find-syms.o: lib/darwin/find-syms.c
	mkdir -p out/lib/darwin
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/darwin/find-syms.o -MMD -MF /Users/a/open/substitute/out/lib/darwin/find-syms.d ./lib/darwin/find-syms.c
-include out/lib/darwin/find-syms.d

out/lib/darwin/inject.o: lib/darwin/inject.c
	mkdir -p out/lib/darwin
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/darwin/inject.o -MMD -MF /Users/a/open/substitute/out/lib/darwin/inject.d ./lib/darwin/inject.c
-include out/lib/darwin/inject.d

out/lib/darwin/interpose.o: lib/darwin/interpose.c
	mkdir -p out/lib/darwin
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/darwin/interpose.o -MMD -MF /Users/a/open/substitute/out/lib/darwin/interpose.d ./lib/darwin/interpose.c
-include out/lib/darwin/interpose.d

out/lib/darwin/objc-asm.o: lib/darwin/objc-asm.S
	mkdir -p out/lib/darwin
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/darwin/objc-asm.o -MMD -MF /Users/a/open/substitute/out/lib/darwin/objc-asm.d ./lib/darwin/objc-asm.S
-include out/lib/darwin/objc-asm.d

out/lib/darwin/objc.o: lib/darwin/objc.c
	mkdir -p out/lib/darwin
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/darwin/objc.o -MMD -MF /Users/a/open/substitute/out/lib/darwin/objc.d ./lib/darwin/objc.c
-include out/lib/darwin/objc.d

out/lib/darwin/read.o: lib/darwin/read.c
	mkdir -p out/lib/darwin
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/darwin/read.o -MMD -MF /Users/a/open/substitute/out/lib/darwin/read.d ./lib/darwin/read.c
-include out/lib/darwin/read.d

out/lib/darwin/substrate-compat.o: lib/darwin/substrate-compat.c
	mkdir -p out/lib/darwin
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/darwin/substrate-compat.o -MMD -MF /Users/a/open/substitute/out/lib/darwin/substrate-compat.d ./lib/darwin/substrate-compat.c
-include out/lib/darwin/substrate-compat.d

out/lib/darwin/execmem.o: lib/darwin/execmem.c
	mkdir -p out/lib/darwin
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/darwin/execmem.o -MMD -MF /Users/a/open/substitute/out/lib/darwin/execmem.d ./lib/darwin/execmem.c
-include out/lib/darwin/execmem.d

out/lib/cbit/vec.o: lib/cbit/vec.c
	mkdir -p out/lib/cbit
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/cbit/vec.o -MMD -MF /Users/a/open/substitute/out/lib/cbit/vec.d ./lib/cbit/vec.c
-include out/lib/cbit/vec.d

out/lib/jump-dis.o: lib/jump-dis.c
	mkdir -p out/lib
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/jump-dis.o -MMD -MF /Users/a/open/substitute/out/lib/jump-dis.d ./lib/jump-dis.c
-include out/lib/jump-dis.d

out/lib/transform-dis.o: lib/transform-dis.c
	mkdir -p out/lib
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/transform-dis.o -MMD -MF /Users/a/open/substitute/out/lib/transform-dis.d ./lib/transform-dis.c
-include out/lib/transform-dis.d

out/lib/hook-functions.o: lib/hook-functions.c
	mkdir -p out/lib
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/hook-functions.o -MMD -MF /Users/a/open/substitute/out/lib/hook-functions.d ./lib/hook-functions.c
-include out/lib/hook-functions.d

out/lib/strerror.o: lib/strerror.c
	mkdir -p out/lib
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/lib/strerror.o -MMD -MF /Users/a/open/substitute/out/lib/strerror.d ./lib/strerror.c
-include out/lib/strerror.d

out/libsubstitute.dylib: out/generated/darwin-inject-asm.o out/lib/darwin/find-syms.o out/lib/darwin/inject.o out/lib/darwin/interpose.o out/lib/darwin/objc-asm.o out/lib/darwin/objc.o out/lib/darwin/read.o out/lib/darwin/substrate-compat.o out/lib/darwin/execmem.o out/lib/cbit/vec.o out/lib/jump-dis.o out/lib/transform-dis.o out/lib/hook-functions.o out/lib/strerror.o ent.plist
	mkdir -p /Users/a/open/substitute/out
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -dynamiclib -o /Users/a/open/substitute/out/libsubstitute.dylib out/generated/darwin-inject-asm.o out/lib/darwin/find-syms.o out/lib/darwin/inject.o out/lib/darwin/interpose.o out/lib/darwin/objc-asm.o out/lib/darwin/objc.o out/lib/darwin/read.o out/lib/darwin/substrate-compat.o out/lib/darwin/execmem.o out/lib/cbit/vec.o out/lib/jump-dis.o out/lib/transform-dis.o out/lib/hook-functions.o out/lib/strerror.o -lobjc -install_name /usr/lib/libsubstitute.0.dylib -dead_strip -O3 -miphoneos-version-min=8.0
	/usr/bin/xcrun --sdk iphoneos ldid -S./ent.plist /Users/a/open/substitute/out/libsubstitute.dylib

out/libsubstitute.0.dylib:
	mkdir -p /Users/a/open/substitute/out
	ln -nfs libsubstitute.dylib /Users/a/open/substitute/out/libsubstitute.0.dylib

out/darwin-bootstrap/safety-dance/AutoGrid.o: darwin-bootstrap/safety-dance/AutoGrid.m
	mkdir -p out/darwin-bootstrap/safety-dance
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fobjc-arc -Wno-unused-parameter -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/darwin-bootstrap/safety-dance/AutoGrid.o -MMD -MF /Users/a/open/substitute/out/darwin-bootstrap/safety-dance/AutoGrid.d ./darwin-bootstrap/safety-dance/AutoGrid.m
-include out/darwin-bootstrap/safety-dance/AutoGrid.d

out/darwin-bootstrap/safety-dance/main.o: darwin-bootstrap/safety-dance/main.m
	mkdir -p out/darwin-bootstrap/safety-dance
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fobjc-arc -Wno-unused-parameter -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/darwin-bootstrap/safety-dance/main.o -MMD -MF /Users/a/open/substitute/out/darwin-bootstrap/safety-dance/main.d ./darwin-bootstrap/safety-dance/main.m
-include out/darwin-bootstrap/safety-dance/main.d

out/SafetyDance.app/SafetyDance: out/darwin-bootstrap/safety-dance/AutoGrid.o out/darwin-bootstrap/safety-dance/main.o ent.plist
	mkdir -p /Users/a/open/substitute/out/SafetyDance.app
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -o /Users/a/open/substitute/out/SafetyDance.app/SafetyDance out/darwin-bootstrap/safety-dance/AutoGrid.o out/darwin-bootstrap/safety-dance/main.o -framework UIKit -framework Foundation -dead_strip -O3 -miphoneos-version-min=8.0
	/usr/bin/xcrun --sdk iphoneos ldid -S./ent.plist /Users/a/open/substitute/out/SafetyDance.app/SafetyDance

out/SafetyDance.app/Info.plist: darwin-bootstrap/safety-dance/Info.plist
	mkdir -p /Users/a/open/substitute/out/SafetyDance.app
	plutil -convert binary1 -o /Users/a/open/substitute/out/SafetyDance.app/Info.plist ./darwin-bootstrap/safety-dance/Info.plist

out/SafetyDance.app/Default.png: darwin-bootstrap/safety-dance/white.png
	mkdir -p /Users/a/open/substitute/out/SafetyDance.app
	cp ./darwin-bootstrap/safety-dance/white.png /Users/a/open/substitute/out/SafetyDance.app/Default.png

out/SafetyDance.app/Default@2x.png: darwin-bootstrap/safety-dance/white.png
	mkdir -p /Users/a/open/substitute/out/SafetyDance.app
	cp ./darwin-bootstrap/safety-dance/white.png /Users/a/open/substitute/out/SafetyDance.app/Default@2x.png

.PHONY: safety-dance
safety-dance: out/darwin-bootstrap/safety-dance/main.o out/darwin-bootstrap/safety-dance/AutoGrid.o

out/darwin-bootstrap/posixspawn-hook.o: darwin-bootstrap/posixspawn-hook.c
	mkdir -p out/darwin-bootstrap
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/darwin-bootstrap/posixspawn-hook.o -MMD -MF /Users/a/open/substitute/out/darwin-bootstrap/posixspawn-hook.d ./darwin-bootstrap/posixspawn-hook.c
-include out/darwin-bootstrap/posixspawn-hook.d

out/posixspawn-hook.dylib: out/libsubstitute.dylib out/darwin-bootstrap/posixspawn-hook.o ent.plist
	mkdir -p /Users/a/open/substitute/out
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -dynamiclib -o /Users/a/open/substitute/out/posixspawn-hook.dylib /Users/a/open/substitute/out/libsubstitute.dylib out/darwin-bootstrap/posixspawn-hook.o -lbsm -dead_strip -O3 -miphoneos-version-min=8.0
	/usr/bin/xcrun --sdk iphoneos ldid -S./ent.plist /Users/a/open/substitute/out/posixspawn-hook.dylib

out/darwin-bootstrap/bundle-loader.o: darwin-bootstrap/bundle-loader.c
	mkdir -p out/darwin-bootstrap
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/darwin-bootstrap/bundle-loader.o -MMD -MF /Users/a/open/substitute/out/darwin-bootstrap/bundle-loader.d ./darwin-bootstrap/bundle-loader.c
-include out/darwin-bootstrap/bundle-loader.d

out/bundle-loader.dylib: out/darwin-bootstrap/bundle-loader.o ent.plist
	mkdir -p /Users/a/open/substitute/out
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -dynamiclib -o /Users/a/open/substitute/out/bundle-loader.dylib out/darwin-bootstrap/bundle-loader.o -dead_strip -O3 -miphoneos-version-min=8.0
	/usr/bin/xcrun --sdk iphoneos ldid -S./ent.plist /Users/a/open/substitute/out/bundle-loader.dylib

out/darwin-bootstrap/unrestrict.o: darwin-bootstrap/unrestrict.c
	mkdir -p out/darwin-bootstrap
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/darwin-bootstrap/unrestrict.o -MMD -MF /Users/a/open/substitute/out/darwin-bootstrap/unrestrict.d ./darwin-bootstrap/unrestrict.c
-include out/darwin-bootstrap/unrestrict.d

out/unrestrict: out/libsubstitute.dylib out/darwin-bootstrap/unrestrict.o ent.plist
	mkdir -p /Users/a/open/substitute/out
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -o /Users/a/open/substitute/out/unrestrict /Users/a/open/substitute/out/libsubstitute.dylib out/darwin-bootstrap/unrestrict.o -dead_strip -O3 -miphoneos-version-min=8.0
	/usr/bin/xcrun --sdk iphoneos ldid -S./ent.plist /Users/a/open/substitute/out/unrestrict

out/darwin-bootstrap/inject-into-launchd.o: darwin-bootstrap/inject-into-launchd.c
	mkdir -p out/darwin-bootstrap
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/darwin-bootstrap/inject-into-launchd.o -MMD -MF /Users/a/open/substitute/out/darwin-bootstrap/inject-into-launchd.d ./darwin-bootstrap/inject-into-launchd.c
-include out/darwin-bootstrap/inject-into-launchd.d

out/inject-into-launchd: out/libsubstitute.dylib out/darwin-bootstrap/inject-into-launchd.o ent.plist
	mkdir -p /Users/a/open/substitute/out
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -o /Users/a/open/substitute/out/inject-into-launchd /Users/a/open/substitute/out/libsubstitute.dylib out/darwin-bootstrap/inject-into-launchd.o -framework IOKit -framework CoreFoundation -dead_strip -O3 -miphoneos-version-min=8.0
	/usr/bin/xcrun --sdk iphoneos ldid -S./ent.plist /Users/a/open/substitute/out/inject-into-launchd

out/darwin-bootstrap/substituted.o: darwin-bootstrap/substituted.m
	mkdir -p out/darwin-bootstrap
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fobjc-arc -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/darwin-bootstrap/substituted.o -MMD -MF /Users/a/open/substitute/out/darwin-bootstrap/substituted.d ./darwin-bootstrap/substituted.m
-include out/darwin-bootstrap/substituted.d

out/substituted: out/libsubstitute.dylib out/darwin-bootstrap/substituted.o ent.plist
	mkdir -p /Users/a/open/substitute/out
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -o /Users/a/open/substitute/out/substituted /Users/a/open/substitute/out/libsubstitute.dylib out/darwin-bootstrap/substituted.o -lbsm -framework Foundation -framework CoreFoundation -dead_strip -O3 -miphoneos-version-min=8.0
	/usr/bin/xcrun --sdk iphoneos ldid -S./ent.plist /Users/a/open/substitute/out/substituted

out/darwin-bootstrap/safemode-ui-hook.o: darwin-bootstrap/safemode-ui-hook.m
	mkdir -p out/darwin-bootstrap
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -Werror -I./lib -I./substrate -I./vendor -fobjc-arc -fvisibility=hidden -O3 -miphoneos-version-min=8.0 -Werror -c -o out/darwin-bootstrap/safemode-ui-hook.o -MMD -MF /Users/a/open/substitute/out/darwin-bootstrap/safemode-ui-hook.d ./darwin-bootstrap/safemode-ui-hook.m
-include out/darwin-bootstrap/safemode-ui-hook.d

out/safemode-ui-hook.dylib: out/libsubstitute.dylib out/darwin-bootstrap/safemode-ui-hook.o ent.plist
	mkdir -p /Users/a/open/substitute/out
	/usr/bin/xcrun --sdk iphoneos cc -arch armv7 -arch arm64 -dynamiclib -o /Users/a/open/substitute/out/safemode-ui-hook.dylib /Users/a/open/substitute/out/libsubstitute.dylib out/darwin-bootstrap/safemode-ui-hook.o -framework Foundation -framework UIKit -dead_strip -O3 -miphoneos-version-min=8.0
	/usr/bin/xcrun --sdk iphoneos ldid -S./ent.plist /Users/a/open/substitute/out/safemode-ui-hook.dylib

Makefile: script/mconfig.py configure
	echo "Running config.status..."
	./config.status

.PHONY: clean
clean:
	rm -f /Users/a/open/substitute/out/SafetyDance.app/Default.png
	rm -f /Users/a/open/substitute/out/SafetyDance.app/Default@2x.png
	rm -f /Users/a/open/substitute/out/SafetyDance.app/Info.plist
	rm -f /Users/a/open/substitute/out/SafetyDance.app/SafetyDance
	rm -f /Users/a/open/substitute/out/bundle-loader.dylib
	rm -f /Users/a/open/substitute/out/inject-into-launchd
	rm -f /Users/a/open/substitute/out/libsubstitute.0.dylib
	rm -f /Users/a/open/substitute/out/libsubstitute.dylib
	rm -f /Users/a/open/substitute/out/posixspawn-hook.dylib
	rm -f /Users/a/open/substitute/out/safemode-ui-hook.dylib
	rm -f /Users/a/open/substitute/out/substituted
	rm -f /Users/a/open/substitute/out/unrestrict
	rm -f out/darwin-bootstrap/bundle-loader.o
	rm -f out/darwin-bootstrap/inject-into-launchd.o
	rm -f out/darwin-bootstrap/posixspawn-hook.o
	rm -f out/darwin-bootstrap/safemode-ui-hook.o
	rm -f out/darwin-bootstrap/safety-dance/AutoGrid.o
	rm -f out/darwin-bootstrap/safety-dance/main.o
	rm -f out/darwin-bootstrap/substituted.o
	rm -f out/darwin-bootstrap/unrestrict.o
	rm -f out/generated/darwin-inject-asm.o
	rm -f out/lib/cbit/vec.o
	rm -f out/lib/darwin/execmem.o
	rm -f out/lib/darwin/find-syms.o
	rm -f out/lib/darwin/inject.o
	rm -f out/lib/darwin/interpose.o
	rm -f out/lib/darwin/objc-asm.o
	rm -f out/lib/darwin/objc.o
	rm -f out/lib/darwin/read.o
	rm -f out/lib/darwin/substrate-compat.o
	rm -f out/lib/hook-functions.o
	rm -f out/lib/jump-dis.o
	rm -f out/lib/strerror.o
	rm -f out/lib/transform-dis.o

.PHONY: distclean
distclean:
	rm -f config.log
	rm -f config.status
	rm -f build.ninja
	rm -f Makefile
	rm -rf /Users/a/open/substitute/out
